services:
  - type: web
    name: cryptowatch-backend
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /api/coins
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: cryptowatch-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://ton-frontend.com
      - key: COINGECKO_API_BASE_URL
        value: https://api.coingecko.com/api/v3

databases:
  - name: cryptowatch-db
    plan: free
    region: frankfurt
    databaseName: cryptowatch
    ipAllowList: []
